---
 - hosts: kartoffel
   roles:
     - ansible-xresources
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux
     - ansible-polybar
     - ansible-zsh

 - hosts: zitrone
   roles:
     - ansible-xresources
     - ansible-vim
     - ansible-i3
     - ansible-termite
     - ansible-neomutt
     - ansible-tmux
     - ansible-polybar
     - ansible-zsh

 - hosts: lauch
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh

 - hosts: birne
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh

 - hosts: kfbox
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh

 - hosts: buche
   roles:
     - ansible-vim
     - ansible-tmux
     - ansible-zsh


